# Configuration of the CI pipeline
name: 'Azure AKS'
canonical: 'stack-aks'
status: 'public'
description: 'Used to deploy an Azure Kubernetes Service cluster with one or more node pools.'
keywords:
  - 'kubernetes'
  - 'aks'
  - 'provider:azure'
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/stack-aks/master/icon.png'
type: 'stack'
technologies:
  - technology: Azure Kubernetes Service
    version: latest
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    aks:
      path: 'terraform/aks.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/aks.tf'
